spring.application.name=projektet_a_secure webshop
spring.datasource.url=jdbc:postgresql://ep-lively-sun-alh92c8y-pooler.c-3.eu-central-1.aws.neon.tech/neondb?&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7nX9bBLJzPlw
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.jpa.hibernate.ddl-auto=update
