name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Debug structure
        run: ls -R


      - name: Build mail module
        run: |
          cd spring-messenger
          mvn clean install


      - name: Build webshop module
        run: |
          cd projektet_a_secure_webshop
          mvn clean package

  
